### PR TITLE
simple addition of directives to baseline implementation

### PR DESCRIPTION
**Pull request by chertio**
Duplicated the xilinx implementation file and added the unroll directive for the loops in the cholesky_basic function -- this problem is reasonably small so this works out fine, larger problems (e.g. 100x100) would have very long synthesis time if completely unrolled

### CODE REVIEW

**Comment by radoye** [comment]
Two questions:
 * you switched back to plain Cholesky? No solving? I'm asking since the top seems to be chol_decomp.
 * is there a way to avoid changing project paths every time we check out ... they are absolute in these files and that's  annoying ...

**Comment by chertio** [comment]
Oh let me do the solving tomorrow, I ll see how it goes

the default project setup using absolute path is dumb....I ll try replace
with relative path and hopefully they work

**Comment by chertio** [comment]
hey, are you sure the top level function for solving is in the repo?
chol_fwbw_solve function doesnt seem to exist

**Comment by chertio** [comment]
umm its in the github, but somehow I didnt get it when I cloned

**Pull request merged**
